### ISSUE TITLE
MCDaemon doesn't retrieve the latest version of vanilla server

### ISSUE THREAD

**Issue by arthurpham** [Finomnis/MCDaemon#1]
For the moment MCDaemon only retrieves minecraft server version 1.5.2 (see the server.log file "Starting minecraft server version 1.5.2") when the latest version from mojang is 1.8.1 (see https://minecraft.net/download).

This is due to the way Mojang changed their launcher and the url to retrieve the server jar changed. The correct json url to query is https://s3.amazonaws.com/Minecraft.Download/versions/versions.json to get the version. See for reference http://gaming.stackexchange.com/questions/123194/is-there-a-way-to-get-the-latest-server-jar-through-a-url-that-doesnt-change

**Comment by Finomnis** [comment]
That's pretty cool. I was searching for something like that json url, but I didn't find it. I'll add that.
Guess vanilla minecraft now gets its own config file after all.

**Comment by Finomnis** [comment]
I found more info here: http://archiveteam.org/index.php?title=Minecraft.net

**Comment by Finomnis** [comment]
Fixed in a4f1d2aaf59d94628982be832f93215afafd31eb.
